### ISSUE TITLE
[BUG] Ao voltar atrás na pilha enquanto nos encontramos no fim da pilha dá um erro

### ISSUE THREAD

**Issue by PedroRomanoBarbosa** [AoDispor/AoDispor-Android#41]

**Comment by bmad4ever** [comment]
Está resolvido para alguns casos. (pesquisas após realização de pesquisas com apenas 1 utilizador)
Ainda não sei poderá acontecer em outras situações...

**Comment by bmad4ever** [comment]
Aparenta estar resolvido, avisem caso volte a ocorrer e tomem nota do erro.
