### ISSUE TITLE
[BUG] Não é possível fazer scroll na descrição dos cartões. 

### ISSUE THREAD

**Issue by VitorSantos1** [AoDispor/AoDispor-Android#47]
Quando um utilizador deseja ver a restante descrição, inicialmente invisível, a acção de descartar cartão é efectuada, quando arrasta o dedo, de cima para baixo.

**Comment by PedroRomanoBarbosa** [comment]
Isso é de propósito para ser mais fácil arrastar o cartão. Para ver a descrição completa é necessário abrir o perfil do profissional clicando no cartão.
