### ISSUE TITLE
Mostrar perfis locais sem necessitar de GPS? 

### ISSUE THREAD

**Issue by VitorSantos1** [AoDispor/AoDispor-Android#48]
Já foi tentado obter a localização através de rede, sem necessitar de GPS? 

Ajuda dev: O course_location consegue set preciso, ao ponto de não ser necessário o fine_location?

**Comment by PedroRomanoBarbosa** [comment]
Penso que a localização através de rede estava já implementada no website, mas não temos isso na aplicação. É algo para pensar.

**Comment by lamelas** [comment]
Correcto, @PedroRomanoBarbosa. No lado do servidor já se usa o IP para encontrar a localização do utilizador.

**Comment by lamelas** [comment]
@VitorSantos1, há alguma boa razão para se usar o coarse em vez do fine? Eu não sou developer Android por isso pode haver alguma razão que me escape.

**Comment by VitorSantos1** [comment]
@lamelas, o coarse permite-te ter uma localização, apesar de não tão precisa, sem ter obrigatoriamente o GPS ligado. Numa aplicação que, aparentemente, não necessite de uma localização precisa; o coarse é o mais imediato - não tendo aqueles passos para ligar o GPS.

**Comment by lamelas** [comment]
@VitorSantos1 sendo que no nosso caso a precisão é importante, acho que mantemos o FINE. Pensei que haveria alguma razão mais obscura que eu não estivesse a ver para usarmos o COARSE. Obrigado pela sugestão, de qualquer das maneiras. :)
