### ISSUE TITLE
Dá para sair do menu de editar profissional quando se está a modificar um campo(nome, profissão e descrição)

### ISSUE THREAD

**Issue by PedroRomanoBarbosa** [AoDispor/AoDispor-Android#60]

**Comment by lamelas** [comment]
Não seria boa ideia, para evitar isto e aquele erro de uma pessoa conseguir aceder ao cartão sem estar autenticada, meter a edição do cartão e a pilha de cartas em duas actividades separadas? Não para a 1.0, mas para o futuro.
