### ISSUE TITLE
Ao editar o título, ele envia para o servidor o valor antigo

### ISSUE THREAD

**Issue by lamelas** [AoDispor/AoDispor-Android#65]
O que diz no título. Troco o título, carrego no botão de gravar ou mesmo no de esconder o teclado e ele envia o valor antigo.

**Comment by PedroRomanoBarbosa** [comment]
Pelo título queres dizer a profissão?

**Comment by lamelas** [comment]
Exacto!


A sábado, 18/02/2017, 20:14, Pedro Romano Barbosa <notifications@github.com>
escreveu:
