### ISSUE TITLE
Fazer upload de uma foto de perfil faz crashar a app

### ISSUE THREAD

**Issue by lamelas** [AoDispor/AoDispor-Android#66]
Isto é aquele problema que nunca ficou resolvido no meu telemóvel. O meu medo é que aconteça em mais modelos.

**Comment by PedroRomanoBarbosa** [comment]
Qual é o erro que te dá no teu telemóvel? É que no meu está a funcionar corretamente.

**Comment by lamelas** [comment]
O mesmo de sempre: aquilo crasha. Deixa-me correr que já te mando o stackdump.

**Comment by lamelas** [comment]
[Está aqui.](https://github.com/AoDispor/AoDispor-Android/files/785913/stackdump.txt) Entretanto ao ver lembrei-me qual é o erro: uma função qualquer chamada `getParcelable()`

**Comment by PedroRomanoBarbosa** [comment]
Sem ter o teu telemóvel para fazer testes vai ser um bocado difícil ver isso. Vou vendo outros problemas e quando estiver contigo tento resolver

**Comment by lamelas** [comment]
Pode ser. Vemos isso amanha.
